version: 2

aliases:
  - &install-chrome
      name: Install Chrome
      command: |
        sudo apt install -y libappindicator3-1
        curl -L -o google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo dpkg -i google-chrome.deb
        sudo sed -i 's|HERE/chrome\"|HERE/chrome\" --disable-setuid-sandbox|g' /opt/google/chrome/google-chrome
        rm google-chrome.deb

  - &restore-cache-src
      key: dependency-cache-{{ checksum "package.json" }}

  - &save-cache-src
      key: dependency-cache-{{ checksum "package.json" }}
      paths:
        - node_modules

defaults: &defaults
  working_directory: /tmp/workspace
  docker:
    - image: circleci/node:10-browsers

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-cache-src
      - run: npm install
      - save_cache: *save-cache-src
      - run: npm run lint
      - run: npm run build
      - run: npm run build -- --prod
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - "*"
  test:
    <<: *defaults
    steps:
      - run: *install-chrome
      - attach_workspace:
          at: /tmp/workspace
      - run: npm run test -- --watch=false --progress=false

workflows:
  version: 2
  build:
    jobs:
      - build
      - test:
          requires:
            - build
